[package]
name = "combinatorial"
version = "0.1.0"
authors = ["Robbie Litchfield"]
edition = "2018"

[dependencies]

[lib]
name = "combinatorial"
path = "src/lib.rs"

[[bin]]
name = "test"
path = "src/main.rs"
